### ISSUE TITLE
Merging back to Apollo Response Cache plugin

### ISSUE THREAD

**Issue by robertu7** [thematters/apollo-response-cache#16]
Since `responseCachePlugin` is highly coupled with `@logCache` and `@purgeCache` directives, we need a discussion on whether and how we merge back to the [official repo](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-plugin-response-cache).

**Comment by guoliu** [comment]
Related discussions: https://github.com/apollographql/apollo-server/issues/3228 https://github.com/apollographql/apollo-server/pull/2437
